### ISSUE TITLE
[meta] 2018年7月目標（もんど担当分）

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#2]
3章をラフに書く（書いておくべき項目を漏らさない感じで）。

issue時の状況
## とりあえず埋まっている
- [3-1](https://github.com/bakera/html-book/blob/master/md_text/3-1.md)
- [3-2](https://github.com/bakera/html-book/blob/master/md_text/3-2.md)
- [3-3](https://github.com/bakera/html-book/blob/master/md_text/3-3.md)
- [3-4](https://github.com/bakera/html-book/blob/master/md_text/3-4.md)
- [3-6](https://github.com/bakera/html-book/blob/master/md_text/3-6.md) （これ以上書くことがあるのか…？）
- [3-8](https://github.com/bakera/html-book/blob/master/md_text/3-8.md)（中身は充実させる必要あり）

## 見出しを充実させる必要あり
- [x] [3-5](https://github.com/bakera/html-book/blob/master/md_text/3-5.md)
- [x] [3-7](https://github.com/bakera/html-book/blob/master/md_text/3-7.md)
- [x] [3-9](https://github.com/bakera/html-book/blob/master/md_text/3-9.md)
- [x] [3-10](https://github.com/bakera/html-book/blob/master/md_text/3-10.md)
- [x] [3-11](https://github.com/bakera/html-book/blob/master/md_text/3-11.md)

**Comment by momdo** [comment]
とりあえず、3章を全部埋めることができた。
まだ執筆していない章の作業を進めるとして、内容を詰めるのは後回しとする。
