### ISSUE TITLE
[meta] 4章の執筆

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#8]
4章をラフに書く（書いておくべき項目を漏らさない感じで）。

とはいっても、このissueを立てた時点で、4-1と4-2はある程度埋まっている。内容を充実させるのに、必要な事項をつめて、執筆をすすめていく。

- [ ] <a href="https://github.com/bakera/html-book/blob/master/md_text/4-1.md">4-1</a>
- [x] <a href="https://github.com/bakera/html-book/blob/master/md_text/4-2.md">4-2</a>
- [x] <a href="https://github.com/bakera/html-book/blob/master/md_text/4-3.md">4-3</a>

**Comment by momdo** [comment]
4-3はとりあえずチェッカーでメッセージが出る類いのものを仮置き。

4-1は現状ある程度埋まっているが、イベントハンドラーコンテンツ属性（`on～`）についても書くのが適当か（現状後回し）
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Event_handlers

**Comment by momdo** [comment]
4-1は加筆していないものの、とりあえず埋まっているので一旦閉じ
